Repository E-Lexis/Doggy-Daycare, pull requests merged in 2022-05, with the labels that each got.

#1 Added basics to README File
  README.md
Labels: documentation

#3 Added a Developers Section
  README.md
Labels: documentation

#4 Added the names of the developers
  README.md
Labels: documentation

#11 Develop to Main
  controllers/api/trainer-routes.js
  models/Trainer.js
  seeds/trainer-seed.js
Labels: enhancement

#14 Develop
  LICENSE
  README.md
  controllers/api/dog-routes.js
  models/Dog.js
  models/index.js
Labels: documentation, enhancement

#15 Develop
  controllers/api/dog-routes.js
  controllers/api/index.js
  seeds/dog-seed.js
  seeds/index.js
Labels: bug

#16 CREATE, UPDATE, and DELETE routes where added
  controllers/api/dog-routes.js
Labels: enhancement

#17 README File
  README.md
Labels: documentation

#18 Feature/signoff to develop
  config/connection.js
  controllers/api/dog-routes.js
  controllers/api/owner-routes.js
  controllers/api/trainer-routes.js
  controllers/home-routes.js
  controllers/index.js
  models/Owner.js
  models/Trainer.js
  models/index.js
  package.json
  public/css/style.css
  public/js/login.js
  seeds/dog-seed.js
  server.js
  utils/auth.js
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
Labels: enhancement

#19 Created the index models
  models/index.js
Labels: enhancement

#21 login routes to user dashboard
  controllers/home-routes.js
  controllers/index.js
  server.js
Labels: bug

#22 Changed the username
  public/js/login.js
Labels: bug

#23 Changed the route in dashboard
  controllers/dashboard-routes.js
  public/js/login.js
Labels: bug

#25 Edited the README File as well as adding two photos
  README.md
  public/img/dashboard.png
  public/img/homePage.png
Labels: documentation

#26 Created the initial files for edit and add; changed the footer for th…
  public/js/addDog.js
  public/js/edit.js
  views/layouts/main.handlebars
  views/owner-dashboard.handlebars
Labels: enhancement

#28 refactored code
  .gitignore
  __tests__/helper.test.js
  config/connection.js
  config/passport.js
  controllers/api/comment-routes.js
  controllers/api/dog-routes.js
  controllers/api/index.js
  controllers/api/owner-routes.js
  controllers/api/trainer-routes.js
  controllers/api/user-routes.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  controllers/index.js
  db/schema.sql
  lib/passwordUtils.js
  models/Appointment.js
  models/Comment.js
  models/Dog.js
  models/Owner.js
  models/Trainer.js
  models/User.js
  models/index.js
  package.json
  public/js/add-dog.js
  public/js/addDog.js
  public/js/comment.js
  public/js/dashboard.js
  public/js/delete-dog.js
  public/js/edit-dog.js
  public/js/edit-user.js
  public/js/edit.js
  public/js/login.js
  public/js/logout.js
  public/js/signup.js
  seeds/appointment-seed.js
  seeds/comment-seed.js
  seeds/dog-seed.js
  seeds/index.js
  seeds/owner-seed.js
  seeds/trainer-seed.js
  seeds/user-seed.js
  server.js
  utils/admin.js
  utils/auth.js
  utils/helpers.js
  views/dashboard.handlebars
  views/edit-dog.handlebars
  views/edit-user.handlebars
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/owner-dashboard.handlebars
  views/owner-login.handlebars
  views/partials/comments.handlebars
  views/partials/dog-info.handlebars
  views/partials/user-info.handlebars
  views/signup.handlebars
  views/single-dog.handlebars
Labels: bug, enhancement

#30 Feature/readme
  README.md
Labels: documentation

#31 Develop
  README.md
Labels: documentation
